Repository chipsalliance/firrtl, pull requests merged in 2018-10, with the labels that each got.

#901 Use "_" for Inline Name Mangling, Respect Namespaces
  src/main/scala/firrtl/Namespace.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/Uniquify.scala
  src/main/scala/firrtl/passes/clocklist/ClockList.scala
  src/test/scala/firrtlTests/FlattenTests.scala
  src/test/scala/firrtlTests/InlineInstancesTests.scala
Labels: API Modification, bugfix, requesting review

#909 Verilog renaming uses "_", works on whole AST
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/passes/Passes.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: API Modification, bugfix, requesting review

#921 Better error message on missing BlackBox resource
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
  src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala
Labels: requesting review

#865 Instance Annotations
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/main/scala/firrtl/annotations/Named.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/annotations/TargetToken.scala
  src/main/scala/firrtl/annotations/analysis/DuplicationHelper.scala
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/Uniquify.scala
  src/main/scala/firrtl/passes/VerilogRename.scala
  src/main/scala/firrtl/passes/wiring/WiringTransform.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/main/scala/firrtl/transforms/OptimizationAnnotations.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/ClockListTests.scala
  src/test/scala/firrtlTests/InlineInstancesTests.scala
  src/test/scala/firrtlTests/RenameMapSpec.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
  src/test/scala/firrtlTests/annotationTests/TargetSpec.scala
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: API Addition (no impact on existing code), DO NOT MERGE, requesting review

#924 Fix TRAVIS_COMMIT_RANGE in .run_chisel_tests, replace ... with ..
  .run_chisel_tests.sh
Labels: bugfix

#927 Fix $TRAVIS_COMMIT_RANGE
  .travis.yml
Labels: requesting review
