Repository chipsalliance/firrtl, pull requests merged in 2018-04, with the labels that each got.

#778 CyclicException identifies a problem node.
  src/main/scala/firrtl/graph/DiGraph.scala
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtlTests/graph/DiGraphTests.scala
Labels: API Addition (no impact on existing code), feature

#787 Fix bug in Constant Propagation for registers propped to zero
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: bugfix, high priority

#795 Fix bug in VerilogMemDelays
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/test/scala/firrtlTests/VerilogMemDelaySpec.scala
Labels: bugfix
