Repository chipsalliance/firrtl, pull requests merged in 2018-02, with the labels that each got.

#424 Replacematcherror - catch exceptions and convert to internal error.
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/main/scala/firrtl/passes/CheckWidths.scala
  src/main/scala/firrtl/passes/ConvertFixedToSInt.scala
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/passes/RemoveValidIf.scala
  src/main/scala/firrtl/passes/Resolves.scala
  src/main/scala/firrtl/passes/Uniquify.scala
  src/main/scala/firrtl/passes/clocklist/ClockList.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/passes/memlib/YamlUtils.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtlTests/InternalErrorSpec.scala
Labels: API Addition (no impact on existing code), enhancement

#717 Add tests for #702. Adds Utility functions. Allows clock muxing in FIRRTL, but not Emitter.
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/passes/Checks.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
  src/main/scala/firrtl/passes/memlib/ResolveMaskGranularity.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ChirrtlMemSpec.scala
  src/test/scala/firrtlTests/UnitTests.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: API Modification, requesting review

#721 Refactor Annotations
  .run_chisel_tests.sh
  build.sbt
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/main/scala/firrtl/annotations/AnnotationYamlProtocol.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/main/scala/firrtl/annotations/Named.scala
  src/main/scala/firrtl/package.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/clocklist/ClockList.scala
  src/main/scala/firrtl/passes/clocklist/ClockListTransform.scala
  src/main/scala/firrtl/passes/memlib/DecorateMems.scala
  src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemTransform.scala
  src/main/scala/firrtl/passes/memlib/ResolveMemoryReference.scala
  src/main/scala/firrtl/passes/wiring/WiringTransform.scala
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/main/scala/firrtl/transforms/Flatten.scala
  src/main/scala/firrtl/transforms/OptimizationAnnotations.scala
  src/test/resources/annotations/InvalidLegacyAnnotations.anno
  src/test/resources/annotations/LegacyAnnotations.anno
  src/test/resources/annotations/SampleAnnotations.anno.json
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/CInferMDirSpec.scala
  src/test/scala/firrtlTests/CheckCombLoopsSpec.scala
  src/test/scala/firrtlTests/ChirrtlMemSpec.scala
  src/test/scala/firrtlTests/DCETests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
  src/test/scala/firrtlTests/FirrtlSpec.scala
  src/test/scala/firrtlTests/InferReadWriteSpec.scala
  src/test/scala/firrtlTests/PassTests.scala
  src/test/scala/firrtlTests/ReplSeqMemTests.scala
  src/test/scala/firrtlTests/UnitTests.scala
  src/test/scala/firrtlTests/WiringTests.scala
  src/test/scala/firrtlTests/annotationTests/TargetDirAnnotationSpec.scala
  src/test/scala/firrtlTests/fixed/FixedPointMathSpec.scala
  src/test/scala/firrtlTests/fixed/RemoveFixedTypeSpec.scala
  src/test/scala/firrtlTests/transforms/BlacklBoxSourceHelperSpec.scala
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: API Modification, enhancement, high priority
