Repository chipsalliance/firrtl, pull requests merged in 2018-03, with the labels that each got.

#750 Fix annotation deserialization of component subfields
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
Labels: bugfix, top priority

#760 Pass up annotations in return value from Driver.execute
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/test/scala/firrtlTests/DriverSpec.scala
Labels: API Addition (no impact on existing code), API Modification

#692 Make Register Update Flattening a Transform and Delete Dangling Nodes
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/FlattenRegUpdate.scala
  src/test/scala/firrtlTests/DCETests.scala
Labels: API Addition (no impact on existing code)
