Repository chipsalliance/firrtl, pull requests merged in 2018-12, with the labels that each got.

#963 Remove side effect from DiGraph sum
  src/main/scala/firrtl/graph/DiGraph.scala
Labels: bugfix, requesting review

#976 Fix NoneCompiler outputForm
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/transforms/IdentityTransform.scala
Labels: API Addition (no impact on existing code), bugfix, requesting review

#962 Enhance CheckCombLoops to support annotated ExtModule paths
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/test/scala/firrtlTests/CheckCombLoopsSpec.scala
Labels: Implementation, requesting review

#961 Small convenience tweaks to IR/WIR APIs
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/ir/IR.scala
Labels: requesting review
