Repository chipsalliance/firrtl, pull requests merged in 2018-05, with the labels that each got.

#806 Bugfix: ports of a temporary name would break const-prop
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: bugfix

#812 Change from Yosys 0.7 to master
  .install_yosys.sh
Labels: high priority

#816 Makes ExpandWhens preserve connect Info's
  .fix_yosys_abc.patch
  .install_yosys.sh
  .travis.yml
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/test/scala/firrtlTests/InfoSpec.scala
Labels: bugfix, feature
