Repository chipsalliance/firrtl, pull requests merged in 2018-11, with the labels that each got.

#928 Dont append to lists
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/LowerTypes.scala
  src/main/scala/firrtl/passes/Passes.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/test/scala/firrtlTests/UnitTests.scala
  src/test/scala/firrtlTests/WidthSpec.scala
Labels: enhancement

#879 [F764.5] Add firrtl.options package, but do not use
  src/main/scala/firrtl/options/OptionParser.scala
  src/main/scala/firrtl/options/OptionsView.scala
  src/main/scala/firrtl/options/Registration.scala
  src/main/scala/firrtl/options/Shell.scala
  src/main/scala/firrtl/options/Stage.scala
  src/test/resources/META-INF/services/firrtl.options.RegisteredLibrary
  src/test/resources/META-INF/services/firrtl.options.RegisteredTransform
  src/test/scala/firrtlTests/options/OptionParserSpec.scala
  src/test/scala/firrtlTests/options/OptionsViewSpec.scala
  src/test/scala/firrtlTests/options/RegistrationSpec.scala
  src/test/scala/firrtlTests/options/ShellSpec.scala
Labels: API Addition (no impact on existing code), requesting review

#919 [F764.6] Add, but do not use Options-mirroring Annotations
  src/main/resources/META-INF/services/firrtl.options.RegisteredLibrary
  src/main/resources/META-INF/services/firrtl.options.RegisteredTransform
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/main/scala/firrtl/package.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/clocklist/ClockListTransform.scala
  src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
  src/main/scala/firrtl/passes/memlib/MemLibOptions.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemTransform.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/test/scala/firrtlTests/annotationTests/TargetDirAnnotationSpec.scala
Labels: API Addition (no impact on existing code), requesting review

#936 Fix bug in TargetDirAnnotation compatibility
  src/main/scala/firrtl/package.scala
Labels: bugfix

#945 Change firrtl.options API, add Phase
  src/main/scala/firrtl/options/OptionsView.scala
  src/main/scala/firrtl/options/Phase.scala
  src/main/scala/firrtl/options/Shell.scala
  src/main/scala/firrtl/options/Stage.scala
  src/main/scala/firrtl/options/StageAnnotations.scala
  src/main/scala/firrtl/options/StageOptions.scala
  src/main/scala/firrtl/options/StageUtils.scala
  src/main/scala/firrtl/options/package.scala
  src/main/scala/firrtl/options/phases/AddDefaults.scala
  src/main/scala/firrtl/options/phases/ConvertLegacyAnnotations.scala
  src/main/scala/firrtl/options/phases/GetIncludes.scala
  src/test/scala/firrtlTests/options/OptionsViewSpec.scala
Labels: API Addition (no impact on existing code), requesting review
