Repository chipsalliance/firrtl, pull requests merged in 2019-07, with the labels that each got.

#1108 Remove shadow type parameter
  src/main/scala/firrtl/Visitor.scala
Labels: Please Merge

#1079 Dependency API
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/graph/DiGraph.scala
  src/main/scala/firrtl/options/DependencyManager.scala
  src/main/scala/firrtl/options/Phase.scala
  src/test/scala/firrtlTests/options/PhaseManagerSpec.scala
Labels: Merge Commit Please

#1118 Remove some warnings
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/PrimOps.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/graph/DiGraph.scala
  src/main/scala/firrtl/graph/EulerTour.scala
  src/main/scala/firrtl/passes/Checks.scala
  src/main/scala/firrtl/passes/InferTypes.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/memlib/DecorateMems.scala
  src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
  src/main/scala/firrtl/passes/memlib/MemIR.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/main/scala/firrtl/passes/wiring/Wiring.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/main/scala/firrtl/transforms/Flatten.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/main/scala/firrtl/transforms/TopWiring.scala
  src/main/scala/logger/Logger.scala
Labels: Please Merge

#1114 Fix typo
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
Labels: Please Merge

#1113 README.md Patches
  README.md
Labels: Merge Commit Please

#967 Fix renaming of annotations with paths
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/test/scala/firrtlTests/RenameMapSpec.scala
Labels: Please Merge

#1111 Add SimplifyMems transform to lower memories without splitting
  src/main/scala/firrtl/transforms/SimplifyMems.scala
  src/test/scala/firrtlTests/SimplifyMemsSpec.scala
Labels: Please Merge

#1126 Fix RenameMap chaining
  src/main/scala/firrtl/RenameMap.scala
  src/test/scala/firrtlTests/RenameMapSpec.scala
Labels: Please Merge

#1052 More constprop on muxes
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
Labels: Please Merge

#1135 Add ExpandConnects to TopWiringTransform fixup
  src/main/scala/firrtl/transforms/TopWiring.scala
  src/test/scala/firrtlTests/transforms/TopWiringTest.scala
Labels: Please Merge, bugfix

#1109 Implement MultiTargetAnnotation
  src/main/scala/firrtl/annotations/Annotation.scala
Labels: Please Merge

#1139 Fix "since" deprecation, should be "1.3" not "1.2"
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
Labels: DO NOT MERGE

#1140 Make write-under-write section for mems in spec
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#1142 io.Source is not closed when used in most common text reading idiom
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/FileUtils.scala
Labels: enhancement
