Repository chipsalliance/firrtl, pull requests merged in 2019-08, with the labels that each got.

#1143 Followup to PR #1142
  build.sbt
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/FileUtils.scala
  src/main/scala/firrtl/options/phases/GetIncludes.scala
  src/main/scala/firrtl/passes/memlib/YamlUtils.scala
  src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/test/scala/firrtl/stage/phases/tests/DriverCompatibilitySpec.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
  src/test/scala/firrtlTests/FirrtlSpec.scala
  src/test/scala/firrtlTests/MultiThreadingSpec.scala
  src/test/scala/firrtlTests/ProtoBufSpec.scala
  src/test/scala/firrtlTests/ReplSeqMemTests.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
  src/test/scala/firrtlTests/transforms/BlackBoxSourceHelperSpec.scala
  src/test/scala/firrtlTests/transforms/TopWiringTest.scala
Labels: enhancement

#1148 DRY check chirrtl
  src/main/scala/firrtl/passes/CheckChirrtl.scala
  src/main/scala/firrtl/passes/Checks.scala
  src/test/scala/firrtlTests/CheckSpec.scala
  src/test/scala/firrtlTests/ChirrtlSpec.scala
  src/test/scala/firrtlTests/InternalErrorSpec.scala
Labels: Please Merge

#1147 Check mems for legal latencies; ban zero write latency.
  spec/spec.pdf
  spec/spec.tex
  src/main/scala/firrtl/passes/Checks.scala
  src/test/scala/firrtlTests/CheckSpec.scala
Labels: Please Merge

#1150 Improve RemoveReset on Invalid Inits
  src/main/scala/firrtl/transforms/RemoveReset.scala
  src/test/scala/firrtlTests/transforms/RemoveResetSpec.scala
Labels: DO NOT MERGE, Merge Commit Please

#1151 Remove unused CheckHighFormLike.IllegalChirrtlMemException
  src/main/scala/firrtl/passes/Checks.scala
Labels: Please Merge
