Repository chipsalliance/firrtl, pull requests merged in 2019-02, with the labels that each got.

#1009 Missed constprop opportunity
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: enhancement, low priority

#1004 Add "mverilog" Compiler Option, MinimumVerilogEmitter
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/passes/Passes.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/CompilerTests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
Labels: Merge Commit Please

#1000 Attempt to deal with timing vagaries in UniquifySpec.quicklyrenamedeepbundles
  src/test/scala/firrtlTests/UniquifySpec.scala
Labels: Please Merge

#984 Correctly handle dots in loaded memory paths
  src/main/scala/firrtl/annotations/LoadMemoryAnnotation.scala
  src/test/scala/firrtlTests/annotationTests/LoadMemoryAnnotationSpec.scala
Labels: Please Merge

#1024 Prevent Flatten from stripping all annotations
  src/main/scala/firrtl/transforms/Flatten.scala
  src/test/scala/firrtlTests/FlattenTests.scala
Labels: Please Merge

#1026 Added mergify configuration
  .mergify.yml
Labels: Please Merge

#1027 Added mergify badge to README
  README.md
Labels: Please Merge

#1025 No time left for you - quickly rename deep bundles still occasionally fails.
  src/test/scala/firrtlTests/UniquifySpec.scala
Labels: Please Merge

#1023 Don't let the main module become deduped out of existence.
  src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: Please Merge

#1029 Bump yosys to 0.8
  .fix_yosys_abc.patch
  .install_yosys.sh
  scripts/formal_equiv.sh
Labels: Please Merge

#867 Stop reporting exceptions in custom transformations as internal errors
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Driver.scala
  src/test/scala/firrtlTests/CustomTransformSpec.scala
  src/test/scala/firrtlTests/InferReadWriteSpec.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
Labels: Please Merge

#956 Add Width Constraints with Annotations
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/Passes.scala
  src/test/scala/firrtlTests/AttachSpec.scala
  src/test/scala/firrtlTests/CheckInitializationSpec.scala
  src/test/scala/firrtlTests/CheckSpec.scala
  src/test/scala/firrtlTests/ChirrtlSpec.scala
  src/test/scala/firrtlTests/ClockListTests.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
  src/test/scala/firrtlTests/ExpandWhensSpec.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/ReplaceAccessesSpec.scala
  src/test/scala/firrtlTests/UnitTests.scala
  src/test/scala/firrtlTests/WidthSpec.scala
  src/test/scala/firrtlTests/WiringTests.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
  src/test/scala/firrtlTests/fixed/FixedTypeInferenceSpec.scala
  src/test/scala/firrtlTests/fixed/RemoveFixedTypeSpec.scala
  src/test/scala/firrtlTests/transforms/InferWidthsWithAnnosSpec.scala
Labels: Please Merge

#548 Run CheckHighForm after all non-emitter transforms in firrtl tests
  src/main/scala/firrtl/passes/Checks.scala
  src/test/scala/firrtlTests/FirrtlSpec.scala
Labels: Please Merge

#1034 Create a simple generic GraphViz renderer for DiGraph
  src/main/scala/firrtl/graph/DiGraph.scala
  src/main/scala/firrtl/graph/RenderDiGraph.scala
  src/test/scala/firrtlTests/graph/DiGraphTests.scala
Labels: Please Merge, enhancement

#1035 Add --nodedup option to facilitate FIRRTL to verilog regression testing.
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: Please Merge

#1039 [ExpandWhens] Don't create nodes to hold Muxes with >0 void cases
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/test/scala/firrtlTests/CheckInitializationSpec.scala
Labels: Please Merge
