Repository chipsalliance/firrtl, pull requests merged in 2019-12, with the labels that each got.

#1190 Logger comment tweaks
  src/main/scala/logger/Logger.scala
Labels: Please Merge

#1265 Remove Stage-global --no-dedup Option
  src/main/scala/firrtl/options/Shell.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
Labels: API Modification, Please Merge, bugfix

#1278 {Firrtl, Circuit}Option should be Unserializable
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
Labels: Please Merge, bugfix

#1282 Fix incorrect ScalaDoc link
  src/main/scala/firrtl/options/StageAnnotations.scala
Labels: Please Merge

#1284 Improve Scaladoc
  src/main/scala/firrtl/options/Phase.scala
Labels: Please Merge
