Repository chipsalliance/firrtl, pull requests merged in 2019-10, with the labels that each got.

#1183 Implement read-first memory behavior in Verilog
  src/main/antlr4/FIRRTL.g4
  src/main/proto/firrtl.proto
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
  src/main/scala/firrtl/passes/memlib/MemIR.scala
  src/main/scala/firrtl/passes/memlib/MemTransformUtils.scala
  src/main/scala/firrtl/passes/memlib/MemUtils.scala
  src/main/scala/firrtl/passes/memlib/ToMemIR.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/main/scala/firrtl/proto/FromProto.scala
  src/main/scala/firrtl/proto/ToProto.scala
  src/test/scala/firrtlTests/ProtoBufSpec.scala
  src/test/scala/firrtlTests/VerilogMemDelaySpec.scala
Labels: DO NOT MERGE, bugfix

#1192 Restore ResolveGenders to its status as a Pass
  src/main/scala/firrtl/passes/Resolves.scala
Labels: bugfix

#1186 Absorb some instance analysis into InstanceGraph, use safer boxed Strings
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/annotations/TargetToken.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
Labels: Please Merge

#870 Upstream intervals
  src/main/antlr4/FIRRTL.g4
  src/main/proto/firrtl.proto
  src/main/scala/firrtl/Implicits.scala
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/Mappers.scala
  src/main/scala/firrtl/PrimOps.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/constraint/Constraint.scala
  src/main/scala/firrtl/constraint/ConstraintSolver.scala
  src/main/scala/firrtl/constraint/Inequality.scala
  src/main/scala/firrtl/constraint/IsAdd.scala
  src/main/scala/firrtl/constraint/IsFloor.scala
  src/main/scala/firrtl/constraint/IsKnown.scala
  src/main/scala/firrtl/constraint/IsMax.scala
  src/main/scala/firrtl/constraint/IsMin.scala
  src/main/scala/firrtl/constraint/IsMul.scala
  src/main/scala/firrtl/constraint/IsNeg.scala
  src/main/scala/firrtl/constraint/IsPow.scala
  src/main/scala/firrtl/constraint/IsVar.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/CheckWidths.scala
  src/main/scala/firrtl/passes/Checks.scala
  src/main/scala/firrtl/passes/ConvertFixedToSInt.scala
  src/main/scala/firrtl/passes/InferBinaryPoints.scala
  src/main/scala/firrtl/passes/InferTypes.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
  src/main/scala/firrtl/passes/RemoveIntervals.scala
  src/main/scala/firrtl/passes/TrimIntervals.scala
  src/main/scala/firrtl/passes/memlib/MemUtils.scala
  src/main/scala/firrtl/proto/ToProto.scala
  src/test/scala/firrtl/stage/phases/tests/DriverCompatibilitySpec.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
  src/test/scala/firrtlTests/ChirrtlSpec.scala
  src/test/scala/firrtlTests/InfoSpec.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/UniquifySpec.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
  src/test/scala/firrtlTests/constraint/InequalitySpec.scala
  src/test/scala/firrtlTests/fixed/FixedTypeInferenceSpec.scala
  src/test/scala/firrtlTests/fixed/RemoveFixedTypeSpec.scala
  src/test/scala/firrtlTests/interval/IntervalMathSpec.scala
  src/test/scala/firrtlTests/interval/IntervalSpec.scala
  src/test/scala/firrtlTests/transforms/InferWidthsWithAnnosSpec.scala
Labels: API Addition (no impact on existing code), API Modification, Feature Request, top priority

#1202 Fix handling of read enables for write-first (default) memories in VerilogMemDelays
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/test/scala/firrtlTests/MemEnFeedbackSpec.scala
  src/test/scala/firrtlTests/MemLatencySpec.scala
  src/test/scala/firrtlTests/execution/ExecutionTestHelper.scala
  src/test/scala/firrtlTests/execution/ParserHelpers.scala
  src/test/scala/firrtlTests/execution/SimpleExecutionTest.scala
  src/test/scala/firrtlTests/execution/VerilogExecution.scala
Labels: DO NOT MERGE, bugfix

#1204 Emit Verilog else-if for Register Updates
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: API Modification, Merge Commit Please

#1208 Enhance CheckCombLoops errors with connection info
  src/main/scala/firrtl/graph/EdgeData.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
Labels: enhancement
