Repository chipsalliance/firrtl, pull requests merged in 2019-11, with the labels that each got.

#1217 Add explicit EOF to top-level parser rule
  src/main/antlr4/FIRRTL.g4
  src/test/scala/firrtlTests/ParserSpec.scala
Labels: Please Merge, enhancement

#1218 Ignore extmodule instances in Flatten
  src/main/scala/firrtl/transforms/Flatten.scala
  src/test/scala/firrtlTests/FlattenTests.scala
Labels: API Addition (no impact on existing code), Please Merge

#1221 Bump to 1.3-SNAPSHOT
  build.sbt
Labels: Please Merge

#1224 Move CheckResets after CheckCombLoops
  src/main/scala/firrtl/LoweringCompilers.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
Labels: Please Merge

#1223 Revert binary-compatibility breaking changes since 1.2.0 and enforce checking
  .run_chisel_tests.sh
  .travis.yml
  build.sbt
  project/plugins.sbt
  src/main/antlr4/FIRRTL.g4
  src/main/proto/firrtl.proto
  src/main/scala/firrtl/Implicits.scala
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/Mappers.scala
  src/main/scala/firrtl/PrimOps.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/constraint/Constraint.scala
  src/main/scala/firrtl/constraint/ConstraintSolver.scala
  src/main/scala/firrtl/constraint/Inequality.scala
  src/main/scala/firrtl/constraint/IsAdd.scala
  src/main/scala/firrtl/constraint/IsFloor.scala
  src/main/scala/firrtl/constraint/IsKnown.scala
  src/main/scala/firrtl/constraint/IsMax.scala
  src/main/scala/firrtl/constraint/IsMin.scala
  src/main/scala/firrtl/constraint/IsMul.scala
  src/main/scala/firrtl/constraint/IsNeg.scala
  src/main/scala/firrtl/constraint/IsPow.scala
  src/main/scala/firrtl/constraint/IsVar.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/CheckWidths.scala
  src/main/scala/firrtl/passes/Checks.scala
  src/main/scala/firrtl/passes/ConvertFixedToSInt.scala
  src/main/scala/firrtl/passes/InferBinaryPoints.scala
  src/main/scala/firrtl/passes/InferTypes.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
  src/main/scala/firrtl/passes/RemoveIntervals.scala
  src/main/scala/firrtl/passes/TrimIntervals.scala
  src/main/scala/firrtl/passes/memlib/MemUtils.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/main/scala/firrtl/proto/ToProto.scala
  src/test/scala/firrtl/stage/phases/tests/DriverCompatibilitySpec.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
  src/test/scala/firrtlTests/ChirrtlSpec.scala
  src/test/scala/firrtlTests/InfoSpec.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/MemEnFeedbackSpec.scala
  src/test/scala/firrtlTests/MemLatencySpec.scala
  src/test/scala/firrtlTests/UniquifySpec.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
  src/test/scala/firrtlTests/constraint/InequalitySpec.scala
  src/test/scala/firrtlTests/execution/ExecutionTestHelper.scala
  src/test/scala/firrtlTests/execution/ParserHelpers.scala
  src/test/scala/firrtlTests/execution/SimpleExecutionTest.scala
  src/test/scala/firrtlTests/execution/VerilogExecution.scala
  src/test/scala/firrtlTests/fixed/FixedTypeInferenceSpec.scala
  src/test/scala/firrtlTests/fixed/RemoveFixedTypeSpec.scala
  src/test/scala/firrtlTests/interval/IntervalMathSpec.scala
  src/test/scala/firrtlTests/interval/IntervalSpec.scala
  src/test/scala/firrtlTests/transforms/InferWidthsWithAnnosSpec.scala
Labels: Merge Commit Please

#1206 Add separate Issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Merge Commit Please

#1191 Add check for multiple sources for same wiring pin
  src/main/scala/firrtl/passes/wiring/WiringTransform.scala
  src/test/scala/firrtlTests/WiringTests.scala
Labels: Please Merge

#1222 Add spec for Analog type and attach statement
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge, requesting review

#1236 [Backport #1222] Add spec for Analog type and attach statement
  spec/spec.pdf
  spec/spec.tex
Labels: Backport

#1228 getSimpleName considered harmful
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/main/scala/firrtl/options/DependencyManager.scala
  src/main/scala/firrtl/stage/package.scala
  src/test/scala/firrtlTests/CustomTransformSpec.scala
Labels: Merge Commit Please, bugfix

#1231 Use Mergify to automate backporting to 1.2.x
  .mergify.yml
Labels: Please Merge, enhancement

#1243 Make updated type info available in VerilogMemDelays
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
Labels: Please Merge

#1256 Try fixing travis binary compatibility check
  .travis.yml
Labels: Please Merge

#1258 Remove scala-logging fully in favor of our own logger
  build.sbt
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/Parser.scala
  src/main/scala/firrtl/PrimOps.scala
  src/test/scala/firrtlTests/FirrtlSpec.scala
Labels: API Modification
