Repository chipsalliance/firrtl, pull requests merged in 2020-09, with the labels that each got.

#1880 InlineBooleanExpressions: test DontTouch
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
Labels: Please Merge

#1883 Legalize mem clocks
  src/main/scala/firrtl/transforms/LegalizeClocksAndAsyncResets.scala
  src/test/scala/firrtlTests/transforms/LegalizeClocksAndAsyncResets.scala
Labels: Merge Commit Please, bugfix

#1885 Better error messages for unserializable annotations
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/test/scala/firrtlTests/annotationTests/JsonProtocolSpec.scala
Labels: Please Merge

#1887 Support binary files in CustomFileEmission
  src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  src/test/scala/firrtlTests/options/phases/WriteOutputAnnotationsSpec.scala
Labels: Please Merge, bugfix

#1869 Add --pretty:no-expr-inlining to prevent expression inlining
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
  src/main/scala/firrtl/stage/package.scala
  src/main/scala/firrtl/stage/transforms/CheckScalaVersion.scala
  src/main/scala/firrtl/transforms/CombineCats.scala
  src/main/scala/firrtl/transforms/InlineBooleanExpressions.scala
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
  src/test/scala/firrtlTests/transforms/CombineCatsSpec.scala
Labels: API Modification

#1882 Loosen inlining restrictions
  src/main/scala/firrtl/transforms/InlineBooleanExpressions.scala
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
Labels: Please Merge

#1891 Make StageOption Unserializable
  src/main/scala/firrtl/options/StageAnnotations.scala
  src/test/scala/firrtlTests/options/phases/WriteOutputAnnotationsSpec.scala
Labels: API Modification, Please Merge

#1716 Hit Connect Case in DedupModuleTests
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: Please Merge, enhancement

#1896 Don't use ResolvedAnnotationPaths in ConstProp nor DCE
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
  src/test/scala/firrtlTests/DCETests.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
Labels: API Modification, Please Merge

#1907 License reference in maven publishing info
  build.sbt
Labels: release issue

#1908 VerilogMemDelays: fix lowering of direct mem-to-mem connections
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/test/scala/firrtlTests/VerilogMemDelaySpec.scala
Labels: bugfix
