Repository chipsalliance/firrtl, pull requests merged in 2020-06, with the labels that each got.

#1654 Fix performance regression in DedupModules
  src/main/scala/firrtl/transforms/Dedup.scala
Labels: Please Merge, bugfix

#1655 Add mapString method to ir.Port
  src/main/scala/firrtl/Mappers.scala
  src/main/scala/firrtl/ir/IR.scala
Labels: API Addition (no impact on existing code), Please Merge

#1651 Revert: Generalize keyword collision to name manipulation, Add {Lower,Upper}CaseNames Transforms
  src/main/scala/firrtl/features/LetterCaseTransform.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/test/scala/firrtlTests/features/LetterCaseTransformSpec.scala
Labels: Please Merge

#1666 Speed up ExpandWhens for very large designs
  src/main/scala/firrtl/passes/ExpandWhens.scala
Labels: Please Merge, enhancement

#1675 Use Travis Workspaces
  .travis.yml
  scripts/formal_equiv.sh
Labels: Please Merge

#1685 Compiler: demote compile time to info instead of error
  src/main/scala/firrtl/stage/phases/Compiler.scala
Labels: Please Merge, enhancement

#1686 delete usages of toSet for determinism
  src/main/scala/firrtl/options/DependencyManager.scala
  src/main/scala/firrtl/options/Phase.scala
Labels: Please Merge

#1643 recore of Attributes
  src/main/scala/firrtl/AddDescriptionNodes.scala
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge

#1645 Support Memory Initialization for Simulation and FPGA Flows
  src/main/scala/firrtl/EmissionOption.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/annotations/MemoryInitAnnotation.scala
  src/main/scala/firrtl/passes/LowerTypes.scala
  src/test/scala/firrtlTests/MemoryInitSpec.scala
  src/test/scala/firrtlTests/execution/VerilogExecution.scala
Labels: Please Merge

#1704 Set prerequisite of -X high to MinimalHighForm
  src/main/scala/firrtl/stage/phases/Compiler.scala
Labels: Please Merge, bugfix

#1717 verification: clarify the meaning of verification statement in warnig message
  src/main/scala/firrtl/transforms/formal/RemoveVerificationStatements.scala
Labels: Please Merge, enhancement

#1638 Refactor ManipulateNames to use Target
  src/main/scala/firrtl/features/LetterCaseTransform.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
  src/test/scala/firrtlTests/features/LetterCaseTransformSpec.scala
  src/test/scala/firrtlTests/transforms/ManipulateNamesSpec.scala
Labels: API Addition (no impact on existing code), bugfix

#1718 Batch renames in LowerTypes
  benchmark/src/main/scala/firrtl/benchmark/hot/TransformBenchmark.scala
  benchmark/src/main/scala/firrtl/benchmark/hot/util/package.scala
  src/main/scala/firrtl/passes/LowerTypes.scala
Labels: Please Merge
