Repository chipsalliance/firrtl, pull requests merged in 2020-01, with the labels that each got.

#1288 Make EmittedAnnotation Unserializable
  src/main/scala/firrtl/Emitter.scala
Labels: Please Merge, bugfix

#1266 Remove incorrect --firrtl-source option
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
Labels: API Modification, Please Merge, bugfix

#1264 Cleanup verilog emitter casts
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/InlineCasts.scala
  src/main/scala/firrtl/transforms/LegalizeClocks.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
  src/test/scala/firrtlTests/transforms/LegalizeClocks.scala
Labels: Merge Commit Please

#1302 Dedup PassTests, add NoCircuitDedupAnnotations
  src/test/scala/firrtlTests/FlattenTests.scala
  src/test/scala/firrtlTests/InlineInstancesTests.scala
  src/test/scala/firrtlTests/PassTests.scala
  src/test/scala/firrtlTests/transforms/GroupComponentsSpec.scala
Labels: Please Merge

#1305 Change default LogLevel to Warn
  src/main/scala/logger/LoggerAnnotations.scala
Labels: Please Merge

#1307 Change LoggerState.globalLevel to Warn
  src/main/scala/logger/Logger.scala
  src/test/scala/loggertests/LoggerSpec.scala
Labels: Backport, bugfix

#1310 Filter ResolvePaths in EliminateTargetPaths
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
Labels: Please Merge, bugfix

#1241 bug fix for freechipsproject/chisel3#1240
  spec/spec.pdf
  spec/spec.tex
  src/main/scala/firrtl/passes/CheckWidths.scala
  src/test/scala/firrtlTests/UnitTests.scala
Labels: API Modification, Please Merge

#1296 Verilog emitter transform InlineBitExtractions
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/transforms/InlineBitExtractions.scala
  src/main/scala/firrtl/transforms/InlineNots.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge, enhancement, good first issue

#1317 Refactoring checkCatArgumentLegality
  src/main/scala/firrtl/Emitter.scala
Labels: Please Merge

#1321 add IsModule, IsMember, CompleteTarget serializers
  src/main/scala/firrtl/annotations/JsonProtocol.scala
Labels: Please Merge
