Repository chipsalliance/firrtl, pull requests merged in 2020-10, with the labels that each got.

#1911 Merge master to 1.4.x for 1.4.0
  .run_chisel_tests.sh
  .travis.yml
  build.sbt
  src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/test/scala/firrtlTests/VerilogMemDelaySpec.scala
Labels: Merge Commit Please

#1915 Fix "fix" for negative literals > 32 bits
  src/main/scala/firrtl/transforms/FixAddingNegativeLiteralsTransform.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Merge Commit Please, release issue

#1918 One more bugfix for 1.4.0
  src/main/scala/firrtl/transforms/FixAddingNegativeLiteralsTransform.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Merge Commit Please, release issue

#1925 Update junit to 4.13.1
  build.sc
Labels: Please Merge

#1926 Make {Stage, FirrtlStage}.run protected
  src/main/scala/firrtl/options/Stage.scala
  src/main/scala/firrtl/stage/FirrtlStage.scala
Labels: Please Merge
