Repository chipsalliance/firrtl, pull requests merged in 2020-03, with the labels that each got.

#1394 EliminateTargetPaths and Unreachable Modules
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
Labels: bugfix

#1413 Remove DiGraph.seededLinearize
  src/main/scala/firrtl/graph/DiGraph.scala
Labels: API Modification, Please Merge

#1414 Update single-line when/else example in spec to match implementation
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#1418 Fix error message for NegWidthException
  src/main/scala/firrtl/passes/Checks.scala
Labels: Please Merge

#1416 Remove RenameMap logging from EliminateTargetPaths
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
Labels: Please Merge

#1422 Revert inline nots
  .travis.yml
  regress/AddNot.fir
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/transforms/InlineNots.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: bugfix

#1423 Clone Verilator from GitHub, fix tag name
  .install_verilator.sh
Labels: Please Merge

#1425 Revert inline nots only 1.2.x (bp #1422)
  .travis.yml
  regress/AddNot.fir
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Backport, Please Merge

#1430 Add firrtl-json serializers
  src/main/scala/firrtl/Parser.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/test/scala/firrtlTests/annotationTests/JsonProtocolSpec.scala
Labels: API Addition (no impact on existing code), Please Merge, enhancement

#1431 Check sign of primop constants where appropriate (bp #1421)
  src/main/scala/firrtl/passes/Checks.scala
  src/test/scala/firrtlTests/CheckSpec.scala
Labels: Backport

#1324 Fix copy-paste error in DiGraph.linearize documentation
  src/main/scala/firrtl/graph/DiGraph.scala
Labels: Please Merge

#1439 [mergify] Update match string for labeling backported PRs
  .mergify.yml
Labels: Please Merge

#1440 Remove dead passes.DeadCodeElimination code
  src/main/scala/firrtl/passes/DeadCodeElimination.scala
Labels: API Modification

#1441 Don't const-prop a register's self-init
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: bugfix

#1447 Revert Compiler.execute to public (was protected)
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/stage/transforms/CatchCustomTransformExceptions.scala
  src/main/scala/firrtl/stage/transforms/TrackTransforms.scala
  src/main/scala/firrtl/stage/transforms/UpdateAnnotations.scala
Labels: API Modification, Please Merge

#1454 Make InlineInstances invalidate ResolveKinds
  src/main/scala/firrtl/passes/Inline.scala
  src/test/scala/firrtlTests/InlineInstancesTests.scala
Labels: bugfix

#1437 Check for name collisions of Modules
  src/main/scala/firrtl/passes/Checks.scala
  src/test/scala/firrtlTests/CheckSpec.scala
Labels: Merge Commit Please, bugfix

#1458 Add method to CheckCompLoops which returns its full netlist
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
Labels: API Addition (no impact on existing code)

#1461 Change annotation logging
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/stage/transforms/UpdateAnnotations.scala
Labels: API Modification

#1449 Remove toNamed (and friends) deprecation.
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/annotations/Target.scala
Labels: Please Merge

#1420 Support Java API doc Scaladoc/Unidoc References
  build.sbt
  src/main/scala/firrtl/options/Exceptions.scala
Labels: Please Merge

#1383 Update scalatest 3.1.0
  build.sbt
  build.sc
  src/test/scala/firrtl/JsonProtocolSpec.scala
  src/test/scala/firrtl/stage/phases/tests/DriverCompatibilitySpec.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtl/testutils/PassTests.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/CheckSpec.scala
  src/test/scala/firrtlTests/CompilerTests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
  src/test/scala/firrtlTests/ExecutionOptionsManagerSpec.scala
  src/test/scala/firrtlTests/FileUtilsSpec.scala
  src/test/scala/firrtlTests/UtilsSpec.scala
  src/test/scala/firrtlTests/VerilogMemDelaySpec.scala
  src/test/scala/firrtlTests/annotationTests/LoadMemoryAnnotationSpec.scala
  src/test/scala/firrtlTests/constraint/InequalitySpec.scala
  src/test/scala/firrtlTests/options/OptionParserSpec.scala
  src/test/scala/firrtlTests/options/OptionsViewSpec.scala
  src/test/scala/firrtlTests/options/PhaseManagerSpec.scala
  src/test/scala/firrtlTests/options/RegistrationSpec.scala
  src/test/scala/firrtlTests/options/ShellSpec.scala
  src/test/scala/firrtlTests/options/phases/AddDefaultsSpec.scala
  src/test/scala/firrtlTests/options/phases/ChecksSpec.scala
  src/test/scala/firrtlTests/options/phases/GetIncludesSpec.scala
  src/test/scala/firrtlTests/options/phases/WriteOutputAnnotationsSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlCliSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddCircuitSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddDefaultsSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddImplicitEmitterSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddImplicitOutputFileSpec.scala
  src/test/scala/firrtlTests/stage/phases/ChecksSpec.scala
  src/test/scala/firrtlTests/stage/phases/CompilerSpec.scala
  src/test/scala/firrtlTests/stage/phases/WriteEmittedSpec.scala
  src/test/scala/loggertests/LoggerSpec.scala
Labels: Please Merge

#1470 Eliminate warnings on `sbt doc` and `sbt unidoc`
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/constraint/ConstraintSolver.scala
  src/main/scala/firrtl/graph/DiGraph.scala
  src/main/scala/firrtl/graph/EdgeData.scala
  src/main/scala/firrtl/graph/RenderDiGraph.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/RemoveIntervals.scala
  src/main/scala/firrtl/stage/phases/CatchExceptions.scala
  src/main/scala/firrtl/stage/transforms/Compiler.scala
  src/main/scala/firrtl/transforms/InferResets.scala
  src/main/scala/firrtl/transforms/InlineBitExtractions.scala
  src/main/scala/firrtl/transforms/InlineCasts.scala
  src/main/scala/firrtl/transforms/PropagatePresetAnnotations.scala
Labels: Please Merge, enhancement

#1473 Bump to Scala 2.12.11
  build.sbt
  build.sc
  project/plugins.sbt
Labels: Please Merge

#1482 Add 'did you update spec' box to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Please Merge

#1483 Add InstaceGraph (Un)?Reachable Helpers (bp #1391)
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/test/scala/firrtlTests/analyses/InstanceGraphTests.scala
Labels: Backport
