Repository chipsalliance/firrtl, pull requests merged in 2020-11, with the labels that each got.

#1920 Add 1.4.x to Mergify
  .mergify.yml
Labels: Please Merge

#1938 Remove caching from RenameMap
  src/main/scala/firrtl/RenameMap.scala
Labels: Please Merge

#1930 -full64 is required to detect VCS.
  src/main/scala/firrtl/FileUtils.scala
Labels: Please Merge

#1943 smt: ensure that all signals have a unique name
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlModuleToTransitionSystemSpec.scala
Labels: Please Merge, bugfix

#1879 Refactor emiter
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/FirrtlException.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/backends/firrtl/FirrtlEmitter.scala
  src/main/scala/firrtl/backends/verilog/MinimumVerilogEmitter.scala
  src/main/scala/firrtl/backends/verilog/SystemVerilogEmitter.scala
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
  src/main/scala/firrtl/package.scala
  src/main/scala/firrtl/passes/InferTypes.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
  src/main/scala/firrtl/transforms/InferResets.scala
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/main/scala/logger/Logger.scala
  src/main/scala/logger/LoggerOptions.scala
Labels: Please Merge

#1942 Fix SMT Memory Bug
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/MemorySpec.scala
Labels: Backport, Please Merge, bugfix

#1950 Fix SMT Memory Bug (bp #1942)
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/MemorySpec.scala
Labels: Backport

#1948 smt: add support for write-first memories
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/MemorySpec.scala
Labels: Please Merge

#1949 Fix RemoveWires handling of invalidated non-UInt wires
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/passes/RemoveValidIf.scala
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtlTests/RemoveWiresSpec.scala
Labels: Please Merge, bugfix

#1962 Switch to allowlist in Travis SNAPSHOT publishing
  .travis.yml
Labels: Please Merge

#1961 make LazyLogging log to console by default.
  src/main/scala/logger/Logger.scala
Labels: Please Merge

#1936 Upgrade antlr4 to 4.8
  build.sbt
  build.sc
Labels: Please Merge

#1960 Fix Type Error fuzzer Example code
  fuzzer/src/test/scala/Example.scala
Labels: Please Merge

#1969 Make MultiTargetAnnotation.targets a def
  src/main/scala/firrtl/annotations/Annotation.scala
Labels: Please Merge

#1983 add weak and strong to Utils.v_keywords
  src/main/scala/firrtl/Utils.scala
Labels: Please Merge

#1905 Add SortModules Transform
  src/main/scala/firrtl/transforms/SortModules.scala
  src/test/scala/firrtlTests/transforms/SortModulesSpec.scala
Labels: API Addition (no impact on existing code), Please Merge
