Repository chipsalliance/firrtl, pull requests merged in 2020-05, with the labels that each got.

#1548 Emitter: guard _RAND_* declarations with ifdef
  src/main/scala/firrtl/Emitter.scala
Labels: Please Merge, enhancement

#1541 Add Some Missing Invalidations
  src/main/scala/firrtl/passes/ExpandConnects.scala
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/passes/SplitExpressions.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/test/scala/firrtlTests/CustomTransformSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
Labels: Please Merge, bugfix

#1547 add Firrtl plugin info for intellij platform
  README.md
Labels: Please Merge

#1550 before/after initial block macros
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge

#1405 Update scalatest to 3.1.1
  build.sbt
  build.sc
  src/test/scala/firrtl/testutils/PassTests.scala
  src/test/scala/firrtlTests/CompilerTests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
  src/test/scala/firrtlTests/options/RegistrationSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
Labels: Backport, Please Merge

#1434 Update protoc-jar to 3.11.4
  project/plugins.sbt
Labels: Backport, Please Merge

#1480 Update moultingyaml to 0.4.2
  build.sbt
  build.sc
Labels: Backport, Please Merge

#1529 Update sbt to 1.3.10
  project/build.properties
Labels: Backport, Please Merge

#1536 Update sbt-scalafix to 0.9.15
  project/plugins.sbt
Labels: Backport, Please Merge

#1565 Clarify spec definition of indentation and when/else indentation
  spec/spec.pdf
  spec/spec.tex
Labels: enhancement

#1543 Add parse_firrtl_transform_log utility script
  scripts/parse_firrtl_transform_log.py
Labels: Please Merge

#1573 Update Travis cache for SBT 1.3
  .travis.yml
Labels: Please Merge

#1575 deprecating BackendCompilationUtilities trait for object
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge

#1578 backporting initialization macro PRs
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Backport

#1579 Make benchmark_cold_compile.py work even if it can't fetch
  benchmark/scripts/benchmark_cold_compile.py
Labels: Please Merge

#1582 Speed up CheckHighForm
  src/main/scala/firrtl/passes/CheckHighForm.scala
Labels: enhancement

#1558 Constant Prop Reduction Operations of Literals
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: enhancement

#1580 Have AppendInfo use MultiInfo, rather than appending with :
  src/main/scala/firrtl/Visitor.scala
  src/test/scala/firrtlTests/InfoSpec.scala
Labels: Please Merge

#1564 Fix typos in the specification.
  spec/spec.tex
Labels: Please Merge

#1596 Backport #1556 to 1.2.x
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/transforms/LegalizeReductions.scala
  src/test/scala/firrtlTests/transforms/LegalizeReductions.scala
Labels: Backport

#1600 consolidated wire+assign to just wire, with expression inlined
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/CompilerTests.scala
  src/test/scala/firrtlTests/DCETests.scala
  src/test/scala/firrtlTests/InfoSpec.scala
  src/test/scala/firrtlTests/ReplaceTruncatingArithmeticSpec.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
  src/test/scala/firrtlTests/transforms/LegalizeClocks.scala
Labels: Please Merge, enhancement

#1604 add Firrtl plugin info for intellij platform (#1547)
  README.md
Labels: Please Merge

#1605 add Firrtl plugin info for intellij platform (#1547)
  README.md
Labels: Please Merge

#1584 Update scalatest to 3.1.2
  build.sbt
  build.sc
Labels: Backport, Please Merge

#1595 [Mergify] Restore backporting to 1.2.x
  .mergify.yml
Labels: Please Merge

#1592 Generalize keyword collision to name manipulation, Add {Lower,Upper}CaseNames Transforms
  src/main/scala/firrtl/features/LetterCaseTransform.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/test/scala/firrtlTests/features/LetterCaseTransformSpec.scala
Labels: API Addition (no impact on existing code), enhancement

#1606 Scala steward 1476
  build.sbt
  build.sc
Labels: Backport, Please Merge

#1607 Scala steward 1560
  build.sbt
  build.sc
Labels: Please Merge

#1623 Backport ResolveKinds improvements from #1475 to 1.2.x
  src/main/scala/firrtl/passes/ResolveKinds.scala
Labels: Backport

#1627 Canonicalize init of regs with zero as reset in RemoveReset
  src/main/scala/firrtl/transforms/RemoveReset.scala
  src/test/scala/firrtlTests/transforms/RemoveResetSpec.scala
Labels: Please Merge, bugfix

#1626 Fix typo in spec description of 'tail'
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#853 Fix equivalence tests
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/IntegrationSpec.scala
Labels: Please Merge

#1594 Don't try deduping the main module of a circuit
  src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: Please Merge

#1635 Add scaladoc for LogicNode and tighten LowForm-only constraint
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
Labels: Please Merge

#1591 RenameMap: remove implicit rename chaining
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/firrtlTests/RenameMapSpec.scala
Labels: API Modification, Please Merge

#1640 Make WrappedTransform work with --class-log-level
  src/main/scala/firrtl/stage/transforms/WrappedTransform.scala
Labels: Please Merge, bugfix
