Repository chipsalliance/firrtl, pull requests merged in 2020-12, with the labels that each got.

#1984 Fix subaccess
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
Labels: Please Merge, bugfix

#1994 smt: add support for uninterpreted ext modules
  src/main/scala/firrtl/backends/experimental/smt/Btor2Serializer.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTExpr.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTExprVisitor.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTLibSerializer.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTTransitionSystemEncoder.scala
  src/main/scala/firrtl/backends/experimental/smt/UninterpretedModuleAnnotation.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/UninterpretedModulesSpec.scala
Labels: Please Merge

#1999 Restore publish settings to before sbt-ci-release
  build.sbt
Labels: Please Merge, bugfix

#2004 Remove explicit pom scm from build.sbt
  build.sbt
Labels: Please Merge, release issue

#1974 Fix Mergify badge in README
  README.md
Labels: Please Merge

#2015 Add newline in the end of LoFIRRTL file
  src/main/scala/firrtl/ir/Serializer.scala
Labels: Please Merge

#2014 fix scaladoc for ReferenceTarget
  src/main/scala/firrtl/annotations/Target.scala
Labels: Please Merge
