Repository chipsalliance/firrtl, pull requests merged in 2020-07, with the labels that each got.

#1726 Fix botched type match in ManipulateNames
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/test/scala/firrtlTests/features/LetterCaseTransformSpec.scala
  src/test/scala/firrtlTests/transforms/ManipulateNamesSpec.scala
Labels: Please Merge, bugfix

#1712 verification: emit mesage as Verilog comment
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/formal/VerificationSpec.scala
Labels: Please Merge

#1694 ir: add faster serializer
  benchmark/src/main/scala/firrtl/benchmark/hot/SerializationBenchmark.scala
  src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/firrtlTests/formal/VerificationSpec.scala
Labels: Please Merge

#1731 dedup: use structural sha256 hash instead of agnostify and serialize
  benchmark/src/main/scala/firrtl/benchmark/hot/TransformBenchmark.scala
  src/main/scala/firrtl/PrimOps.scala
  src/main/scala/firrtl/ir/StructuralHash.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/firrtl/ir/StructuralHashSpec.scala
Labels: Please Merge

#1752 Remove Left Over References to Gender in Code
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
Labels: API Modification, Please Merge

#1761 add .bloop and .metals to .gitignore
  .gitignore
Labels: Please Merge, enhancement

#1762 Change ProtoBuf generated directory
  build.sbt
Labels: Please Merge

#1724 Specify execution order of side-effect-having statements
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#1735 Fix parsing of info on multi-line registers
  src/main/scala/firrtl/Visitor.scala
  src/test/scala/firrtlTests/ParserSpec.scala
Labels: Please Merge

#1750 Make TopWiringTransform run before LowerTypes
  src/main/scala/firrtl/transforms/TopWiring.scala
Labels: Please Merge, bugfix

#1690 ir: store FileInfo string in escaped format
  spec/spec.pdf
  spec/spec.tex
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/ir/Serializer.scala
  src/main/scala/firrtl/proto/FromProto.scala
  src/main/scala/firrtl/proto/ToProto.scala
  src/test/scala/firrtlTests/InfoSpec.scala
  src/test/scala/firrtlTests/ParserSpec.scala
  src/test/scala/firrtlTests/ProtoBufSpec.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge

#1753 Remove overlapping inputForm=LowForm tests
  src/test/scala/firrtlTests/CustomTransformSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
Labels: Merge Commit Please, enhancement

#1743 Propagate source locators to register update always blocks
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/FlattenRegUpdate.scala
  src/main/scala/firrtl/transforms/RemoveReset.scala
  src/test/scala/firrtlTests/InfoSpec.scala
Labels: Please Merge

#1772 Cross-build unidoc in CI
  .travis.yml
Labels: Please Merge, enhancement

#1732 Faster dedup instance graph
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/analyses/InstanceKeyGraph.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/test/scala/firrtlTests/analyses/InstanceKeyGraphSpec.scala
Labels: API Addition (no impact on existing code), Please Merge

#1775 Make InferWidths thread safe
  src/main/scala/firrtl/passes/InferWidths.scala
Labels: Please Merge, bugfix

#1701 [1.3.x] RemoveIntervals: fixup kinds of refs to replaced nodes
  src/main/scala/firrtl/passes/RemoveIntervals.scala
  src/test/scala/firrtlTests/interval/IntervalSpec.scala
Labels: Please Merge

#1782 Update negative literal emission
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Please Merge, bugfix

#1745 mask bits when propagating bitwise ops
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Please Merge, bugfix

#1746 fix reduction op bug ConstantPropagation
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Please Merge, bugfix

#1785 Fix sign extension issue in Emitter
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Please Merge, bugfix

#1754 Integrate new transforms with firrtl.stage.Forms
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/test/scala/firrtlTests/CustomTransformSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
Labels: Please Merge, bugfix

#1795 Fix incorrect error message
  src/main/scala/firrtl/passes/CheckWidths.scala
Labels: Please Merge

#1776 RenameMapSpec: try rename instance and port
  src/test/scala/firrtlTests/RenameMapSpec.scala
Labels: Please Merge

#1769 InferTypes: fix bugs with unknown widths on ports and memories
  src/main/scala/firrtl/passes/InferTypes.scala
  src/main/scala/firrtl/passes/ResolveFlows.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/RemoveWiresSpec.scala
  src/test/scala/firrtlTests/passes/InferTypesFlowsAndKindsSpec.scala
Labels: Please Merge

#1797 RemoveWires: improve dependencies and declare ResolveKinds as an invalidation
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
Labels: Please Merge

#1799 WiringTransform: fix non-determinism
  src/main/scala/firrtl/passes/wiring/Wiring.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/test/scala/firrtlTests/WiringTests.scala
Labels: API Deprecation, Please Merge, bugfix

#1796 Scala 2.13 support
  .travis.yml
  build.sbt
  project/plugins.sbt
  src/main/scala/firrtl/AddDescriptionNodes.scala
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/analyses/InstanceKeyGraph.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/main/scala/firrtl/graph/EulerTour.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/options/OptionParser.scala
  src/main/scala/firrtl/options/Phase.scala
  src/main/scala/firrtl/options/Shell.scala
  src/main/scala/firrtl/passes/CheckHighForm.scala
  src/main/scala/firrtl/passes/CheckInitialization.scala
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/Pass.scala
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
  src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
  src/main/scala/firrtl/passes/memlib/MemConf.scala
  src/main/scala/firrtl/passes/memlib/MemIR.scala
  src/main/scala/firrtl/passes/memlib/ResolveMemoryReference.scala
  src/main/scala/firrtl/passes/wiring/Wiring.scala
  src/main/scala/firrtl/proto/FromProto.scala
  src/main/scala/firrtl/stage/phases/Compiler.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/main/scala/firrtl/transforms/FlattenRegUpdate.scala
  src/main/scala/firrtl/transforms/GroupComponents.scala
  src/main/scala/firrtl/transforms/InferResets.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/firrtl/transforms/PropagatePresetAnnotations.scala
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtlTests/MultiThreadingSpec.scala
  src/test/scala/firrtlTests/ParserSpec.scala
  src/test/scala/firrtlTests/RemoveWiresSpec.scala
  src/test/scala/firrtlTests/interval/IntervalMathSpec.scala
  src/test/scala/firrtlTests/options/OptionParserSpec.scala
  src/test/scala/firrtlTests/options/PhaseManagerSpec.scala
Labels: Merge Commit Please, enhancement

#1809 ir: use Serializer.serialize where possible
  src/main/scala/firrtl/AddDescriptionNodes.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/ir/Serializer.scala
  src/main/scala/firrtl/passes/memlib/MemIR.scala
  src/test/scala/firrtlTests/fixed/FixedSerializationSpec.scala
Labels: Please Merge, bugfix

#1603 [WIP] Implement CircuitGraph and IRLookup to firrtl.analyses
  src/main/scala/firrtl/analyses/CircuitGraph.scala
  src/main/scala/firrtl/analyses/ConnectionGraph.scala
  src/main/scala/firrtl/analyses/IRLookup.scala
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/graph/DiGraph.scala
  src/test/scala/firrtlTests/analyses/CircuitGraphSpec.scala
  src/test/scala/firrtlTests/analyses/ConnectionGraphSpec.scala
  src/test/scala/firrtlTests/analyses/IRLookupSpec.scala
  src/test/scala/firrtlTests/transforms/GroupComponentsSpec.scala
Labels: Please Merge

#1812 [1.2.x] Update negative literal emission (#1782)
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Backport, Please Merge, bugfix

#1813 CircuitGraph: remove fields from public API
  src/main/scala/firrtl/analyses/CircuitGraph.scala
Labels: Please Merge

#1810 [1.3.x] fix reduction op bug ConstantPropagation (#1746)
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Please Merge

#1727 Avoid repeated inlining in FlattenRegUpdate
  src/main/scala/firrtl/transforms/FlattenRegUpdate.scala
  src/test/scala/firrtlTests/RegisterUpdateSpec.scala
Labels: Please Merge

#1816 Fixed typo in fixed-point type parameter examples
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge, bug
