Repository chipsalliance/firrtl, pull requests merged in 2020-08, with the labels that each got.

#1734 Error on ExtModules w/ same defname, diff. ports
  src/main/scala/firrtl/passes/CheckHighForm.scala
  src/test/resources/blackboxes/LargeParam.v
  src/test/resources/blackboxes/LargeParamTester.fir
  src/test/scala/firrtlTests/CheckSpec.scala
  src/test/scala/firrtlTests/transforms/DedupTests.scala
Labels: Please Merge, bugfix

#1800 Deprecate InstanceGraph
  src/main/scala/firrtl/analyses/CircuitGraph.scala
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/analyses/InstanceKeyGraph.scala
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/wiring/Wiring.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/firrtl/transforms/RenameModules.scala
  src/main/scala/firrtl/transforms/TopWiring.scala
  src/test/scala/firrtlTests/analyses/InstanceKeyGraphSpec.scala
Labels: Please Merge, enhancement

#1824 ir: add UseSerializer mixin trait
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/ir/IR.scala
Labels: Please Merge, enhancement

#1791 Add deprecations for more firrtl.Compiler methods
  src/main/scala/firrtl/Compiler.scala
Labels: Please Merge

#1829 ExpandWhens: VerificationStatements should be part of the simlist
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/test/scala/firrtlTests/formal/VerificationSpec.scala
Labels: Please Merge, bugfix

#1835 stage: allow a RunFirrtlTransformAnnotation(_:Emitter) annotation to be used in place of a CompilerAnnotation
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlOptions.scala
  src/main/scala/firrtl/stage/package.scala
  src/main/scala/firrtl/stage/phases/AddDefaults.scala
  src/main/scala/firrtl/stage/phases/AddImplicitEmitter.scala
  src/main/scala/firrtl/stage/phases/Checks.scala
  src/main/scala/firrtl/stage/phases/Compiler.scala
  src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddDefaultsSpec.scala
Labels: Please Merge, enhancement

#1277 File Serialization of Annotations
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/options/StageAnnotations.scala
  src/main/scala/firrtl/options/StageOptions.scala
  src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlStage.scala
  src/main/scala/firrtl/stage/package.scala
  src/main/scala/firrtl/stage/phases/Compiler.scala
  src/main/scala/firrtl/stage/phases/WriteEmitted.scala
  src/test/scala/firrtl/stage/phases/tests/DriverCompatibilitySpec.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/execution/VerilogExecution.scala
  src/test/scala/firrtlTests/options/phases/WriteOutputAnnotationsSpec.scala
  src/test/scala/firrtlTests/transforms/LegalizeReductions.scala
Labels: API Addition (no impact on existing code), API Modification, Merge Commit Please, Please Merge, bugfix

#1840 Strip dependencies from BlackBoxSourceHelper
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
Labels: Please Merge

#1784 Combined Uniquify and LowerTypes pass
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/analyses/SymbolTable.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/CheckHighForm.scala
  src/main/scala/firrtl/passes/CheckTypes.scala
  src/main/scala/firrtl/passes/ExpandWhens.scala
  src/main/scala/firrtl/passes/InferBinaryPoints.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/LowerTypes.scala
  src/main/scala/firrtl/passes/TrimIntervals.scala
  src/main/scala/firrtl/passes/Uniquify.scala
  src/main/scala/firrtl/passes/ZeroWidth.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/main/scala/firrtl/transforms/InferResets.scala
  src/main/scala/firrtl/transforms/TopWiring.scala
  src/test/scala/firrtl/analysis/SymbolTableSpec.scala
  src/test/scala/firrtl/passes/LowerTypesSpec.scala
  src/test/scala/firrtlTests/ExpandWhensSpec.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/MemoryInitSpec.scala
  src/test/scala/firrtlTests/transforms/GroupComponentsSpec.scala
Labels: Please Merge

#1837 Update scalacheck-1-14, ... to 3.1.3.0
  build.sbt
  build.sc
Labels: Please Merge

#1834 Update sbt-buildinfo to 0.10.0
  project/plugins.sbt
Labels: Please Merge

#1692 Update json4s-native to 3.6.9
  build.sbt
  build.sc
Labels: Please Merge

#1720 Update antlr4-runtime to 4.7.2
  build.sc
Labels: Please Merge

#1311 Cleanup Named Targets
  src/main/scala/firrtl/annotations/transforms/CleanupNamedTargets.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/annotationTests/CleanupNamedTargetsSpec.scala
Labels: Merge Commit Please, Please Merge, bugfix

#1833 Remove LegacyAnnotation and [most] MoultingYaml
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/main/scala/firrtl/annotations/AnnotationYamlProtocol.scala
  src/main/scala/firrtl/options/Stage.scala
  src/main/scala/firrtl/options/phases/AddDefaults.scala
  src/main/scala/firrtl/options/phases/Checks.scala
  src/main/scala/firrtl/options/phases/ConvertLegacyAnnotations.scala
  src/main/scala/firrtl/options/phases/GetIncludes.scala
  src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/test/resources/annotations/InvalidLegacyAnnotations.anno
  src/test/resources/annotations/LegacyAnnotations.anno
  src/test/resources/annotations/SampleAnnotations.anno
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
  src/test/scala/firrtlTests/FileUtilsSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
Labels: API Modification, Please Merge

#1845 Rollback scalatest to avoid printing bug
  build.sbt
Labels: Please Merge, bugfix

#1842 Deprecate support for Scala 2.11
  build.sbt
  src/main/scala/firrtl/passes/CheckChirrtl.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
  src/main/scala/firrtl/stage/package.scala
  src/main/scala/firrtl/stage/transforms/CheckScalaVersion.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
Labels: Please Merge

#1847 Bump Scala 2.12.12
  build.sbt
  build.sc
Labels: Please Merge

#1839 tests: Decrease Dependency on Deprecated APIs
  src/test/scala/firrtl/testutils/LeanTransformSpec.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
  src/test/scala/firrtlTests/CheckCombLoopsSpec.scala
  src/test/scala/firrtlTests/ChirrtlMemSpec.scala
  src/test/scala/firrtlTests/CompilerTests.scala
Labels: Please Merge

#1826 SMT Backend
  .install_z3.sh
  .travis.yml
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/backends/experimental/smt/Btor2Serializer.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemantics.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTEmitter.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTExpr.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTExprVisitor.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTLibSerializer.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTTransitionSystemEncoder.scala
  src/main/scala/firrtl/backends/experimental/smt/StutteringClockTransform.scala
  src/test/scala/firrtl/backends/experimental/smt/Btor2Spec.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemanticsSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlModuleToTransitionSystemSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/SMTBackendBaseSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/SMTLibSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/AsyncResetSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/EndToEndSMTSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/MemorySpec.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/RequiresZ3.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/SMTCompilationTest.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/UndefinedFirrtlSpec.scala
Labels: API Addition (no impact on existing code), Please Merge

#1857 Make Serializer support custom FirrtlNodes
  src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/firrtlTests/SerializerSpec.scala
Labels: Please Merge, bugfix

#1867 Scalafmt check all
  .travis.yml
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
  src/test/scala/firrtlTests/SerializerSpec.scala
Labels: Please Merge, bugfix

#1866 smt: ignore clock signals when converting to transition system
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlModuleToTransitionSystemSpec.scala
Labels: Please Merge, bugfix

#1870 Deprecate CompilerAnnotation
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
  src/main/scala/firrtl/stage/FirrtlStage.scala
  src/main/scala/firrtl/stage/phases/AddDefaults.scala
  src/main/scala/firrtl/stage/phases/Checks.scala
  src/main/scala/firrtl/stage/phases/ConvertCompilerAnnotations.scala
  src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
  src/test/scala/firrtl/stage/phases/tests/ConvertCompilerAnnotationsSpec.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddDefaultsSpec.scala
  src/test/scala/firrtlTests/stage/phases/ChecksSpec.scala
Labels: Please Merge

#1871 Fix mill re-download external jar every time.
  build.sc
Labels: Please Merge

#1868 FlattenSpec: flattening a module with no instaces should be a no-op
  src/main/scala/firrtl/passes/Inline.scala
  src/test/scala/firrtlTests/FlattenTests.scala
Labels: Please Merge

#1875 Restrict boolean inlining to avoid context-sensitive width bugs
  src/main/scala/firrtl/transforms/InlineBooleanExpressions.scala
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
Labels: Merge Commit Please

#1874 Emitter: add missing parenthesize calls
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/transforms/InlineBooleanExpressions.scala
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
Labels: bugfix
