Repository chipsalliance/firrtl, pull requests merged in 2020-04, with the labels that each got.

#1493 Disable unidoc -Xfatal-warning for Scala 2.11
  build.sbt
Labels: Please Merge

#1495 Add Release Notes section and check-box for checklist.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Please Merge

#1450 Fix dynamic SubAccess of zero-length vectors
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/passes/ZeroLengthVecs.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/ZeroLengthVecsSpec.scala
Labels: Please Merge, bugfix, requesting review

#1502 Add ground type serializer
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/test/scala/firrtlTests/annotationTests/JsonProtocolSpec.scala
Labels: API Addition (no impact on existing code), Please Merge

#1496 Split Passes.scala into separate files
  src/main/scala/firrtl/passes/ExpandConnects.scala
  src/main/scala/firrtl/passes/Legalize.scala
  src/main/scala/firrtl/passes/Pass.scala
  src/main/scala/firrtl/passes/Passes.scala
  src/main/scala/firrtl/passes/PullMuxes.scala
  src/main/scala/firrtl/passes/ToWorkingIR.scala
  src/main/scala/firrtl/passes/VerilogPrep.scala
Labels: Please Merge

#1504 EliminateTargetPaths: don't duplicate modules with only one instance
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
Labels: Please Merge, bugfix

#1456 [spec] Add Fixed to spec
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge, requesting review

#1510 Verilog Emitter: move asyncInitials inside initial block RANDOMIZE ifdef
  src/main/scala/firrtl/Emitter.scala
Labels: Please Merge

#1512 Fix mixed -E and -e emission
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
Labels: bugfix

#1523 Allow casts in AsyncReset literal value check
  src/main/scala/firrtl/checks/CheckResets.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
Labels: Please Merge, bugfix
