Repository chipsalliance/firrtl, pull requests merged in 2020-02, with the labels that each got.

#1349 Fix conversion of Reference-containing expressions to ReferenceTargets
  src/main/scala/firrtl/Utils.scala
Labels: Please Merge, bugfix

#1323 Dedup: check if moduleOpt exists before getting
  src/main/scala/firrtl/transforms/Dedup.scala
Labels: Please Merge

#1359 Emit 'else' case for trivial-valued async reset regs to avoid latches
  src/main/scala/firrtl/Emitter.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
Labels: Please Merge

#1362 Change zero-width base case for Andr
  spec/spec.pdf
  spec/spec.tex
  src/main/scala/firrtl/passes/ZeroWidth.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
Labels: API Modification, Merge Commit Please, bugfix

#1355 Add constant prop to async regs
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/AsyncResetSpec.scala
Labels: Please Merge

#1370 Rename Modules Duplicated by EliminateTargetPaths
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/test/scala/firrtlTests/annotationTests/EliminateTargetPathsSpec.scala
Labels: API Addition (no impact on existing code), Merge Commit Please, bugfix

#1378 [spec] Change sub(UInt, UInt) output type to UInt
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#1326 Update sbt-scalafix to 0.9.11
  project/plugins.sbt
Labels: Please Merge

#1327 Update sbt-assembly to 0.14.10
  project/plugins.sbt
Labels: Please Merge

#1328 Update sbt-buildinfo to 0.9.0
  project/plugins.sbt
Labels: Please Merge

#1329 Update sbt-unidoc to 0.4.2
  project/plugins.sbt
Labels: Please Merge

#1330 Update protoc-jar to 3.11.1
  project/plugins.sbt
Labels: Please Merge

#1332 Update junit to 4.13
  build.sbt
Labels: Please Merge

#1333 Update commons-text to 1.8
  build.sbt
Labels: Please Merge

#1375 Add reviewer checklist / update contributor checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Please Merge

#1367 Support MemConfs with very deep memories
  src/main/scala/firrtl/passes/memlib/MemConf.scala
Labels: Please Merge

#1335 Update sbt-scoverage to 1.6.1
  project/plugins.sbt
Labels: Please Merge

#1336 Update scalacheck to 1.14.3
  build.sbt
Labels: Please Merge

#1374 Fixing lint error: x + -1
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/transforms/FixAddingNegativeLiteralsTransform.scala
  src/main/scala/firrtl/transforms/ReplaceTruncatingArithmetic.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge

#1354 Update sbt to 1.3.8
  project/build.properties
Labels: Please Merge

#1381 Removed unused imports in src/test/
  src/test/scala/firrtl/JsonProtocolSpec.scala
  src/test/scala/firrtlTests/AttachSpec.scala
  src/test/scala/firrtlTests/CInferMDirSpec.scala
  src/test/scala/firrtlTests/CheckCombLoopsSpec.scala
  src/test/scala/firrtlTests/CheckInitializationSpec.scala
  src/test/scala/firrtlTests/ChirrtlMemSpec.scala
  src/test/scala/firrtlTests/CompilerTests.scala
  src/test/scala/firrtlTests/CustomTransformSpec.scala
  src/test/scala/firrtlTests/DCETests.scala
  src/test/scala/firrtlTests/DriverSpec.scala
  src/test/scala/firrtlTests/ExpandWhensSpec.scala
  src/test/scala/firrtlTests/ExtModuleTests.scala
  src/test/scala/firrtlTests/FeatureSpec.scala
  src/test/scala/firrtlTests/FlattenTests.scala
  src/test/scala/firrtlTests/InferReadWriteSpec.scala
  src/test/scala/firrtlTests/InlineInstancesTests.scala
  src/test/scala/firrtlTests/IntegrationSpec.scala
  src/test/scala/firrtlTests/LegalizeSpec.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/PassTests.scala
  src/test/scala/firrtlTests/RemoveWiresSpec.scala
  src/test/scala/firrtlTests/ReplaceAccessesSpec.scala
  src/test/scala/firrtlTests/ReplaceTruncatingArithmeticSpec.scala
  src/test/scala/firrtlTests/SimplifyMemsSpec.scala
  src/test/scala/firrtlTests/StringSpec.scala
  src/test/scala/firrtlTests/UniquifySpec.scala
  src/test/scala/firrtlTests/UnitTests.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
  src/test/scala/firrtlTests/WidthSpec.scala
  src/test/scala/firrtlTests/WiringTests.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
  src/test/scala/firrtlTests/execution/VerilogExecution.scala
  src/test/scala/firrtlTests/fixed/FixedPointMathSpec.scala
  src/test/scala/firrtlTests/fixed/FixedTypeInferenceSpec.scala
  src/test/scala/firrtlTests/fixed/RemoveFixedTypeSpec.scala
  src/test/scala/firrtlTests/interval/IntervalMathSpec.scala
  src/test/scala/firrtlTests/interval/IntervalSpec.scala
  src/test/scala/firrtlTests/options/RegistrationSpec.scala
  src/test/scala/firrtlTests/options/phases/WriteOutputAnnotationsSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlOptionsViewSpec.scala
  src/test/scala/firrtlTests/stage/phases/AddCircuitSpec.scala
  src/test/scala/firrtlTests/stage/phases/ChecksSpec.scala
  src/test/scala/firrtlTests/stage/phases/CompilerSpec.scala
  src/test/scala/firrtlTests/transforms/InferWidthsWithAnnosSpec.scala
  src/test/scala/firrtlTests/transforms/TopWiringTest.scala
Labels: Please Merge

#1387 Include Dead Modules in InstanceGraph.staticInstanceCount
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/test/scala/firrtlTests/analyses/InstanceGraphTests.scala
Labels: API Modification, Merge Commit Please, bugfix

#1331 Update sbt-antlr4 to 0.8.2
  project/plugins.sbt
Labels: Please Merge

#1345 Update sbt-unidoc to 0.4.3
  project/plugins.sbt
Labels: Please Merge

#1286 Repl seq mem renaming
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/passes/memlib/ResolveMemoryReference.scala
  src/test/scala/firrtlTests/ReplSeqMemTests.scala
Labels: Please Merge

#1388 Allow self renames
  src/main/scala/firrtl/RenameMap.scala
  src/test/scala/firrtlTests/RenameMapSpec.scala
Labels: API Modification, Merge Commit Please, bugfix

#1391 Add InstaceGraph (Un)?Reachable Helpers
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/test/scala/firrtlTests/analyses/InstanceGraphTests.scala
Labels: API Addition (no impact on existing code)

#1382 Update ScalaTest deprecations.
  src/test/scala/firrtlTests/FirrtlSpec.scala
Labels: Please Merge

#1396 Remove last connect semantics from reset inference
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/passes/RemoveValidIf.scala
  src/main/scala/firrtl/transforms/InferResets.scala
  src/test/scala/firrtlTests/InferResetsSpec.scala
Labels: bugfix

#1399 Revert "Repl seq mem renaming"
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/passes/memlib/ResolveMemoryReference.scala
  src/test/scala/firrtlTests/ReplSeqMemTests.scala
Labels: Please Merge

#1401 Add more docs / tests for DiGraph reachableFrom method
  src/main/scala/firrtl/graph/DiGraph.scala
  src/test/scala/firrtlTests/graph/DiGraphTests.scala
Labels: Please Merge

#1357 Omnibus Dependency API Updates
  src/main/scala/firrtl/options/DependencyManager.scala
  src/main/scala/firrtl/options/Phase.scala
  src/main/scala/firrtl/options/phases/AddDefaults.scala
  src/main/scala/firrtl/options/phases/Checks.scala
  src/main/scala/firrtl/options/phases/ConvertLegacyAnnotations.scala
  src/main/scala/firrtl/options/phases/DeletedWrapper.scala
  src/main/scala/firrtl/options/phases/GetIncludes.scala
  src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  src/test/scala/firrtlTests/options/PhaseManagerSpec.scala
Labels: API Addition (no impact on existing code), API Modification, Merge Commit Please

#1392 Short Circuit resolvePaths if no Targets
  src/main/scala/firrtl/Compiler.scala
Labels: Please Merge, bugfix
