Repository chipsalliance/firrtl, pull requests merged in 2021-03, with the labels that each got.

#2098 Fix CI Checks (bp #2097)
  .github/workflows/test.yml
  src/main/scala/firrtl/graph/DiGraph.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/VerilogEquivalenceSpec.scala
Labels: Backport

#2062 Remove Scala 2.11
  .github/workflows/test.yml
  build.sbt
  build.sc
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/transforms/CheckScalaVersion.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/SMTCompilationTest.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
Labels: Please Merge

#2100 Fix ProtoBuf conversions for Verification IR
  src/main/proto/firrtl.proto
  src/main/scala/firrtl/proto/FromProto.scala
  src/main/scala/firrtl/proto/ToProto.scala
  src/test/scala/firrtlTests/ProtoBufSpec.scala
Labels: bugfix

#2099 CSE SubAccesses
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/main/scala/firrtl/transforms/CSESubAccesses.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/transforms/CSESubAccessesSpec.scala
Labels: Please Merge

#2095 SMT Backend: move undefined memory behavior modelling to firrtl IR level
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/WIR.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/main/scala/firrtl/backends/experimental/smt/random/DefRandom.scala
  src/main/scala/firrtl/backends/experimental/smt/random/UndefinedMemoryBehaviorPass.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/ir/Serializer.scala
  src/main/scala/firrtl/passes/ResolveKinds.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtl/backends/experimental/smt/random/UndefinedMemoryBehaviorSpec.scala
Labels: Please Merge

#2105 SMT: memory port inout fields cannot be used as RHS expressions
  src/main/scala/firrtl/backends/experimental/smt/random/UndefinedMemoryBehaviorPass.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/MemorySpec.scala
  src/test/scala/firrtl/backends/experimental/smt/random/UndefinedMemoryBehaviorSpec.scala
Labels: Please Merge

#2104 SMT Backend: model Invalid and Division by Zero with DefRandom nodes
  src/main/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemantics.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/main/scala/firrtl/backends/experimental/smt/random/InvalidToRandomPass.scala
  src/test/scala/firrtl/backends/experimental/smt/random/InvalidToRandomSpec.scala
Labels: Please Merge

#2107 Create annotation to allow inline readmem in Verilog
  .gitignore
  src/main/scala/firrtl/EmissionOption.scala
  src/main/scala/firrtl/annotations/MemoryInitAnnotation.scala
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
  src/test/scala/firrtlTests/MemoryInitSpec.scala
Labels: Please Merge

#2109 Fix the readmem statements in nested "initial begin" block
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
Labels: Please Merge, bugfix

#2112 Fix CSESubAccesses for SubAccesses with flips
  src/main/scala/firrtl/transforms/CSESubAccesses.scala
  src/test/scala/firrtlTests/transforms/CSESubAccessesSpec.scala
Labels: Please Merge, bugfix, high priority

#2116 Fix cat of zero-width SInt
  src/main/scala/firrtl/passes/ZeroWidth.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
Labels: Please Merge

#2120 Fix width of constant propagation of SInt with zero
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: bugfix

#2124 Fix issue where inlined cvt could cause crash
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
  src/test/scala/firrtlTests/InlineBooleanExpressionsSpec.scala
Labels: bugfix

#2130 Ensure InlineCasts does not inline complex Expressions
  src/main/scala/firrtl/transforms/InlineCasts.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/InlineCastsSpec.scala
Labels: bugfix

#2147 Fix mill compile
  .github/workflows/test.yml
  build.sc
Labels: Please Merge

#2153 Fix bug in zero-width memory removal
  src/main/scala/firrtl/passes/ZeroWidth.scala
  src/test/scala/firrtlTests/ZeroWidthTests.scala
Labels: Please Merge, bugfix

#2150 Add NoConstantPropagationAnnotation to disable constatnt propagation
  src/main/resources/META-INF/services/firrtl.options.RegisteredTransform
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/OptimizationAnnotations.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: API Deprecation, Please Merge

#2157 Fix RemoveAccesses, delete CSESubAccesses
  src/main/scala/firrtl/passes/RemoveAccesses.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/main/scala/firrtl/transforms/CSESubAccesses.scala
  src/test/scala/firrtlTests/LowerTypesSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/UnitTests.scala
  src/test/scala/firrtlTests/passes/RemoveAccessesSpec.scala
  src/test/scala/firrtlTests/transforms/CSESubAccessesSpec.scala
Labels: Please Merge, bugfix, release issue

#2136 Update protobuf-java to 3.15.6
  build.sc
Labels: Please Merge

#2165 Fix Mill support for non-M1 Macs
  build.sc
Labels: Please Merge
