Repository chipsalliance/firrtl, pull requests merged in 2021-12, with the labels that each got.

#2442 Update os-lib to 0.8.0
  build.sbt
  build.sc
Labels: Please Merge

#2441 Update sbt to 1.5.6
  project/build.properties
Labels: Please Merge

#2393 Modify and optimize performance of propagate annotations
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/package.scala
  src/main/scala/firrtl/stage/transforms/UpdateAnnotations.scala
  src/main/scala/firrtl/transforms/DedupAnnotations.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
Labels: API Modification

#2445 Remove some printlns in tests
  src/test/scala/firrtl/backends/experimental/rtlil/end2end/RtlilEquivalenceTest.scala
  src/test/scala/firrtlTests/SeparateWriteClocksSpec.scala
Labels: Please Merge

#2444 Deprecate all mutable methods on RenameMap and add MutableRenameMap
  src/main/scala/firrtl/RenameMap.scala
  src/main/scala/firrtl/annotations/transforms/CleanupNamedTargets.scala
  src/main/scala/firrtl/annotations/transforms/EliminateTargetPaths.scala
  src/main/scala/firrtl/backends/experimental/smt/StutteringClockTransform.scala
  src/main/scala/firrtl/passes/Inline.scala
  src/main/scala/firrtl/passes/LowerTypes.scala
  src/main/scala/firrtl/passes/RemoveCHIRRTL.scala
  src/main/scala/firrtl/passes/ZeroWidth.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/Dedup.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/firrtl/transforms/SimplifyMems.scala
  src/test/scala/firrtl/passes/LowerTypesSpec.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/MutableRenameMapSpec.scala
  src/test/scala/firrtlTests/transforms/ManipulateNamesSpec.scala
Labels: Please Merge, API Deprecation

#2440 Fix width of signed addition when input to mux
  .github/workflows/test.yml
  src/main/scala/firrtl/passes/SplitExpressions.scala
  src/test/scala/firrtlTests/VerilogEquivalenceSpec.scala
Labels: Skip Formal CI

#2447 smt: deal correctly with negative SInt literals
  src/main/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemantics.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemanticsSpec.scala
Labels: bugfix

#2449 disable random should not contain useInitAsPreset.
  src/main/scala/firrtl/Emitter.scala
Labels: bugfix
