Repository chipsalliance/firrtl, pull requests merged in 2021-08, with the labels that each got.

#2305 Update spec to disallow 0-bit mux sel
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#2304 add emitter for optimized low firrtl
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemantics.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/main/scala/firrtl/backends/firrtl/FirrtlEmitter.scala
  src/main/scala/firrtl/backends/verilog/LegalizeVerilog.scala
  src/main/scala/firrtl/checks/CheckResets.scala
  src/main/scala/firrtl/passes/CommonSubexpressionElimination.scala
  src/main/scala/firrtl/passes/Legalize.scala
  src/main/scala/firrtl/passes/LegalizeConnects.scala
  src/main/scala/firrtl/passes/PadWidths.scala
  src/main/scala/firrtl/passes/RemoveValidIf.scala
  src/main/scala/firrtl/passes/SplitExpressions.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemTransform.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/main/scala/firrtl/transforms/CheckCombLoops.scala
  src/main/scala/firrtl/transforms/CombineCats.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/DeadCodeElimination.scala
  src/main/scala/firrtl/transforms/RemoveReset.scala
  src/main/scala/firrtl/transforms/RemoveWires.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemanticsSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/random/InvalidToRandomSpec.scala
  src/test/scala/firrtlTests/LoFirrtlOptimizedEmitterTests.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
  src/test/scala/firrtlTests/PadWidthsTests.scala
  src/test/scala/firrtlTests/RemoveWiresSpec.scala
  src/test/scala/firrtlTests/VerilogMemDelaySpec.scala
Labels: Please Merge

#2310 remove LoweringCompilersSpec
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
Labels: Please Merge

#2308 Skip Formal CI checks via Github Actions not commit message
  .github/workflows/test.yml
  .run_formal_checks.sh
Labels: Skip Formal CI

#2307 Fix backporting issues for attribute anno deduplication
  src/main/scala/firrtl/AddDescriptionNodes.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
  src/main/scala/firrtl/transforms/DedupAnnotations.scala
Labels: Skip Formal CI

#2319 Fix Specification Memory Port Types
  spec/spec.pdf
  spec/spec.tex
Labels: Please Merge

#2291 Implement NoCommonSubexpressionElimination
  src/main/scala/firrtl/passes/CommonSubexpressionElimination.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
Labels: API Addition (no impact on existing code), Please Merge

#2323 PropagatePresetAnnotations: remove false prerequisites
  src/main/scala/firrtl/transforms/PropagatePresetAnnotations.scala
Labels: Please Merge

#2324 PropagatePresetAnnotations: remove dep. on SplitExpressions and PadWidths
  src/main/scala/firrtl/transforms/PropagatePresetAnnotations.scala
Labels: Please Merge

#2325 [smt] PropagatePresetAnnotations is now a real prereq
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemanticsSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlModuleToTransitionSystemSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/SMTBackendHelpers.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/EndToEndSMTSpec.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/MemorySpec.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/UndefinedFirrtlSpec.scala
Labels: Please Merge

#2326 [smt] make SMTLib + Btor2 emitters public objects
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/backends/experimental/smt/SMTEmitter.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/test/scala/firrtl/backends/experimental/smt/end2end/EndToEndSMTSpec.scala
Labels: Please Merge

#2276 prefer to using using system protoc and antlr4 in mill
  build.sc
Labels: Please Merge

#2332 Fix Serializer for single indented DefModule emission
  src/main/scala/firrtl/ir/Serializer.scala
  src/test/scala/firrtlTests/SerializerSpec.scala
Labels: bugfix, Please Merge

#2334 Add BufferedCustomFileEmission
  src/main/scala/firrtl/options/StageAnnotations.scala
  src/main/scala/firrtl/options/phases/WriteOutputAnnotations.scala
  src/test/scala/firrtlTests/options/phases/WriteOutputAnnotationsSpec.scala
Labels: Please Merge
