Repository chipsalliance/firrtl, pull requests merged in 2021-04, with the labels that each got.

#2111 Add -fpga flag to enable FPGA-oriented compilation strategies (currently for memories)
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
  src/main/scala/firrtl/passes/memlib/InferReadWrite.scala
  src/main/scala/firrtl/passes/memlib/SeparateWriteClocks.scala
  src/main/scala/firrtl/passes/memlib/SetDefaultReadUnderWrite.scala
  src/main/scala/firrtl/passes/memlib/VerilogMemDelays.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
  src/main/scala/firrtl/stage/FirrtlCompilerTargets.scala
  src/main/scala/firrtl/transforms/SimplifyMems.scala
  src/test/scala/firrtlTests/InferReadWriteSpec.scala
  src/test/scala/firrtlTests/InfoSpec.scala
  src/test/scala/firrtlTests/SeparateWriteClocksSpec.scala
Labels: Merge Commit Please

#2146 Deprecate InlineCasts, add InlineAcrossCasts
  src/main/scala/firrtl/AddDescriptionNodes.scala
  src/main/scala/firrtl/passes/VerilogModulusCleanup.scala
  src/main/scala/firrtl/passes/VerilogPrep.scala
  src/main/scala/firrtl/stage/Forms.scala
  src/main/scala/firrtl/transforms/FlattenRegUpdate.scala
  src/main/scala/firrtl/transforms/InlineCasts.scala
  src/main/scala/firrtl/transforms/LegalizeClocksAndAsyncResets.scala
  src/main/scala/firrtl/transforms/RemoveKeywordCollisions.scala
  src/main/scala/firrtl/transforms/package.scala
  src/test/scala/firrtlTests/InlineAcrossCastsSpec.scala
  src/test/scala/firrtlTests/LoweringCompilersSpec.scala
Labels: Please Merge

#2175 smt: use existing bitWidth API
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlExpressionSemantics.scala
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
Labels: Implementation, Please Merge

#2177 Add indent parameter to Serializer.serialize()
  src/main/scala/firrtl/ir/Serializer.scala
Labels: API Addition (no impact on existing code)

#2179 Fix signedness of xor const prop with zero
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: Please Merge

#2190 Hoist Transform timing to the Phase level
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/options/DependencyManager.scala
  src/main/scala/firrtl/stage/transforms/UpdateAnnotations.scala
  src/main/scala/logger/Logger.scala
Labels: Please Merge

#2196 Fix CheckWidths error message for uninferred width
  src/main/scala/firrtl/passes/CheckWidths.scala
Labels: Please Merge

#2199 Deprecate memlib APIs.
  src/main/scala/firrtl/passes/memlib/CreateMemoryAnnotations.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemTransform.scala
  src/test/scala/firrtlTests/ReplSeqMemTests.scala
Labels: API Deprecation, Please Merge

#2191 Memlib Refactor
  src/main/scala/firrtl/passes/memlib/CreateMemoryAnnotations.scala
  src/main/scala/firrtl/passes/memlib/DumpMemoryAnnotations.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemMacros.scala
  src/main/scala/firrtl/passes/memlib/ReplaceMemTransform.scala
  src/test/scala/firrtlTests/ReplSeqMemTests.scala
Labels: API Modification, Please Merge

#2194 Update scalatest to 3.2.8
  build.sbt
  build.sc
Labels: Please Merge

#2163 Update scala-parallel-collections to 1.0.2
  build.sbt
  build.sc
Labels: Please Merge

#2204 Update sbt-scoverage to 1.7.0
  project/plugins.sbt
Labels: Please Merge

#2137 Update antlr4, antlr4-runtime to 4.9.2
  build.sbt
  build.sc
Labels: Please Merge

#2161 Update sbt-scalafix to 0.9.27
  project/plugins.sbt
Labels: Please Merge

#2148 Update sbt-ci-release to 1.5.7
  project/plugins.sbt
Labels: Please Merge

#2134 Update sbt-protobuf to 0.7.0
  project/plugins.sbt
Labels: Please Merge

#1730 Update sbt to 1.3.13
  project/build.properties
Labels: Please Merge

#2138 Update json4s-native to 3.6.11
  build.sbt
  build.sc
Labels: Please Merge

#2205 Update sbt to 1.5.1
  project/build.properties
Labels: Please Merge
