Repository chipsalliance/firrtl, pull requests merged in 2021-11, with the labels that each got.

#2405 BlackBoxSourceHelper: ensure trailing newline in .f file
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
  src/test/scala/firrtlTests/transforms/BlackBoxSourceHelperSpec.scala
Labels: Please Merge

#2412 ci: use official action to install oss cad tools
  .github/workflows/test.yml
Labels: Please Merge

#2407 Update antlr4, antlr4-runtime to 4.9.3
  build.sbt
  build.sc
Labels: Please Merge

#2402 Update sbt-scoverage to 1.9.2
  project/plugins.sbt
Labels: Please Merge

#2406 Update json4s-native to 3.6.12
  build.sbt
  build.sc
Labels: Please Merge

#2394 Update sbt-unidoc to 0.5.0
  project/plugins.sbt
Labels: Please Merge

#2387 Let firrtl based applications run despite loading unknown annotations
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/annotations/AnnotationUtils.scala
  src/main/scala/firrtl/annotations/JsonProtocol.scala
  src/main/scala/firrtl/options/phases/GetIncludes.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
  src/main/scala/firrtl/stage/package.scala
  src/test/scala/firrtlTests/AnnotationTests.scala
  src/test/scala/firrtlTests/annotationTests/UnrecognizedAnnotationSpec.scala
Labels: API Addition (no impact on existing code), Please Merge

#2396 Disable random init
  src/main/scala/firrtl/EmissionOption.scala
  src/main/scala/firrtl/Emitter.scala
  src/main/scala/firrtl/backends/experimental/rtlil/RtlilEmitter.scala
  src/main/scala/firrtl/backends/verilog/VerilogEmitter.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
Labels: Please Merge

#1706 Update sbt-assembly to 1.1.0
  project/plugins.sbt
Labels: Please Merge

#1789 Update commons-text to 1.9
  build.sbt
  build.sc
Labels: Please Merge

#2417 Update sbt-scalafmt to 2.4.4
  project/plugins.sbt
Labels: Please Merge

#2378 Update sbt-protobuf to 0.7.1
  project/plugins.sbt
Labels: Please Merge

#2385 Update sbt-mima-plugin to 1.0.1
  project/plugins.sbt
Labels: Please Merge

#2377 Update scala-parallel-collections to 1.0.4
  build.sbt
  build.sc
Labels: Please Merge

#2364 Update sbt-ci-release to 1.5.9
  project/plugins.sbt
Labels: Please Merge

#1850 Update scalacheck-1-15, ... to 3.2.10.0
  build.sbt
  build.sc
Labels: Please Merge

#2420 [deprecation clean up] remove deprecated API in firrtl.Utils
  src/main/scala/firrtl/Utils.scala
Labels: Please Merge

#2421 [deprecation clean up] remove firrtl.FIRRTLException
  src/main/scala/firrtl/FirrtlException.scala
  src/main/scala/firrtl/stage/phases/CatchExceptions.scala
Labels: Please Merge

#2424 [deprecation clean up] remove firrtl.transforms.InlineAcrossCastsTransform.
  src/main/scala/firrtl/transforms/InlineAcrossCastsTransform.scala
  src/main/scala/firrtl/transforms/package.scala
Labels: Please Merge

#2425 [deprecation clean up] remove firrtl.transforms.InferResets.DifferingDriverTypesException
  src/main/scala/firrtl/transforms/InferResets.scala
Labels: Please Merge

#2426 [deprecation clean up] remove firrtl.transforms.BlackBoxSourceHelper.fileListName.
  src/main/scala/firrtl/transforms/BlackBoxSourceHelper.scala
Labels: Please Merge

#2419 [deprecation clean up] Remove firrtl.Driver.
  src/main/scala/firrtl/Driver.scala
  src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
  src/main/scala/firrtl/stage/transforms/CatchCustomTransformExceptions.scala
Labels: Please Merge

#2422 [deprecation clean up] remove firrtl.ExecutionOptionsManager
  src/main/scala/firrtl/ExecutionOptionsManager.scala
  src/main/scala/firrtl/options/StageAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/package.scala
  src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
  src/main/scala/logger/Logger.scala
  src/main/scala/logger/LoggerAnnotations.scala
  src/test/scala/firrtlTests/ExecutionOptionsManagerSpec.scala
  src/test/scala/firrtlTests/ParserSpec.scala
  src/test/scala/loggertests/LoggerSpec.scala
Labels: API Modification

#2431 Update sbt-scalafix to 0.9.33
  project/plugins.sbt
Labels: Please Merge

#2423 [deprecation clean up] remove trait firrtl.util.BackendCompilationUtilities
  src/main/scala/firrtl/util/BackendCompilationUtilities.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/CheckCombLoopsSpec.scala
  src/test/scala/firrtlTests/DCETests.scala
  src/test/scala/firrtlTests/IntegrationSpec.scala
  src/test/scala/firrtlTests/StringSpec.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
  src/test/scala/firrtlTests/execution/SimpleExecutionTest.scala
  src/test/scala/firrtlTests/execution/VerilogExecution.scala
  src/test/scala/firrtlTests/options/phases/GetIncludesSpec.scala
  src/test/scala/firrtlTests/stage/FirrtlMainSpec.scala
  src/test/scala/firrtlTests/transforms/LegalizeReductions.scala
  src/test/scala/firrtlTests/transforms/TopWiringTest.scala
Labels: API Modification, Please Merge
