Repository chipsalliance/firrtl, pull requests merged in 2021-01, with the labels that each got.

#2036 smt: run DeadCodeElimination after PropagatePresetAnnotations
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystemPassSpec.scala
Labels: Please Merge

#2044 Switch from Travis to Github Actions CI (bp #2041)
  .github/workflows/test.yml
  .mergify.yml
  .run_chisel_tests.sh
  .run_formal_checks.sh
  .travis.yml
  project/plugins.sbt
  scripts/formal_equiv.sh
Labels: Backport

#2045 Switch from Travis to Github Actions CI (bp #2041)
  .github/workflows/test.yml
  .mergify.yml
  .run_chisel_tests.sh
  .run_formal_checks.sh
  .travis.yml
  project/plugins.sbt
  scripts/formal_equiv.sh
Labels: Backport

#2046 Switch from Travis to Github Actions CI (bp #2041)
  .github/workflows/test.yml
  .mergify.yml
  .run_chisel_tests.sh
  .run_formal_checks.sh
  .travis.yml
  project/plugins.sbt
  scripts/formal_equiv.sh
Labels: Backport

#2047 Restore scalafmt CI check
  .github/workflows/test.yml
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystemPassSpec.scala
Labels: Please Merge

#2049 Restore scalafmt CI check (bp #2047)
  .github/workflows/test.yml
  src/main/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystem.scala
  src/test/scala/firrtl/backends/experimental/smt/FirrtlToTransitionSystemPassSpec.scala
Labels: Backport

#2040 Add --dont-fold option to disable folding specific prim ops
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/FirrtlCli.scala
  src/main/scala/firrtl/stage/package.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/test/scala/firrtlTests/ConstantPropagationTests.scala
Labels: API Addition (no impact on existing code), Please Merge

#2032 Cleanup some warnings
  src/main/scala/firrtl/Compiler.scala
  src/main/scala/firrtl/Utils.scala
  src/main/scala/firrtl/Visitor.scala
  src/main/scala/firrtl/analyses/ConnectionGraph.scala
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/annotations/Annotation.scala
  src/main/scala/firrtl/annotations/Target.scala
  src/main/scala/firrtl/backends/firrtl/FirrtlEmitter.scala
  src/main/scala/firrtl/ir/IR.scala
  src/main/scala/firrtl/passes/CInferMDir.scala
  src/main/scala/firrtl/passes/CheckHighForm.scala
  src/main/scala/firrtl/passes/InferWidths.scala
  src/main/scala/firrtl/passes/clocklist/RemoveAllButClocks.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/main/scala/firrtl/proto/FromProto.scala
Labels: Please Merge

#2056 Fix post-merge publishing (bp #2055)
  .github/workflows/test.yml
  build.sbt
  src/main/scala/firrtl/FileUtils.scala
  src/main/scala/firrtl/LexerHelper.scala
  src/main/scala/firrtl/LoweringCompilers.scala
  src/main/scala/firrtl/analyses/ConnectionGraph.scala
  src/main/scala/firrtl/analyses/InstanceGraph.scala
  src/main/scala/firrtl/analyses/InstanceKeyGraph.scala
  src/main/scala/firrtl/graph/DiGraph.scala
  src/main/scala/firrtl/ir/Serializer.scala
  src/main/scala/firrtl/options/DependencyManager.scala
  src/main/scala/firrtl/options/Stage.scala
  src/main/scala/firrtl/passes/wiring/WiringUtils.scala
  src/main/scala/firrtl/stage/FirrtlAnnotations.scala
  src/main/scala/firrtl/stage/phases/DriverCompatibility.scala
  src/main/scala/firrtl/transforms/ConstantPropagation.scala
  src/main/scala/firrtl/transforms/ManipulateNames.scala
  src/main/scala/logger/LoggerOptions.scala
  src/main/scala/tutorial/lesson1-circuit-traversal/AnalyzeCircuit.scala
Labels: Backport

#2058 Stop padding multiply and divide ops
  src/main/scala/firrtl/passes/PadWidths.scala
  src/test/scala/firrtl/testutils/FirrtlSpec.scala
  src/test/scala/firrtlTests/VerilogEmitterTests.scala
  src/test/scala/firrtlTests/VerilogEquivalenceSpec.scala
Labels: bugfix, release issue
